name: CI/CD for Spring Boot CRM

on:
  push:
    branches:
      - main
      - dev
      - 'feature/**'
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Compile project
        run: mvn clean compile

      - name: Run unit tests
        run: mvn verify

      - name: Upload JaCoCo report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

  generate-openapi:
    runs-on: ubuntu-latest
    needs: build-test
    if: github.ref == 'refs/heads/dev' || github.event.pull_request.base.ref == 'dev'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Start Spring Boot app in background
        run: |
          nohup mvn spring-boot:run -Dspring-boot.run.profiles=test -DskipTests &

      - name: Wait for app to start
        run: sleep 20

      - name: Fetch OpenAPI spec
        run: curl http://localhost:8080/v3/api-docs -o target/openapi.json

      - name: Upload OpenAPI spec
        uses: actions/upload-artifact@v4
        with:
          name: openapi-json
          path: target/openapi.json
